import SwiftUI

struct TitleView: View {
    @State var screen: String
    var body: some View {
        if(screen == "one" || screen == "two")
        {
            VStack{
                HStack{
                    Text("TELL US")
                        .font(.custom("Termina Test-Black", size: 40))
                        .fontWeight(.heavy)
                        .foregroundColor(Color.init(hex: "7743DB"))
                        .padding(.vertical, 100)
                        .offset(x:19, y:250)
                        .multilineTextAlignment(.leading)
                        .truncationMode(.tail)
                        .fixedSize()
                        .lineLimit(1)
                    
                    Text("ABOUT")
                        .font(.custom("Termina Test-Black", size: 40))
                        .fontWeight(.heavy)
                        .foregroundColor(Color.white)
                        .padding(.vertical, 140)
                        .offset(x:19, y:250)
                        .multilineTextAlignment(.leading)
                        .truncationMode(.tail)
                        .fixedSize()
                        .lineLimit(1)
                        .frame(maxWidth: .infinity)
                        .shadow(color: Color.black.opacity(0.3), radius: 2, x: 2, y: 2)
                        .background(
                            Text("ABOUT")
                                .font(.custom("Termina Test-Black", size: 40))
                                .fontWeight(.heavy)
                                .foregroundColor(Color.init(hex: "7743DB"))
                                .multilineTextAlignment(.leading)
                                .frame(maxWidth: .infinity)
                                .blur(radius: 0.8)
                                .offset(x:19, y:250)
                                .padding(.vertical, 100)
                        )
                }
                
                .frame(width: 350)
                
                HStack{
                    Text("US")
                        .font(.custom("Termina Test-Black", size: 40))
                        .fontWeight(.heavy)
                        .foregroundColor(Color.white)
                        .padding(.vertical, 100)
                        .offset(x:19, y:-3)
                        .multilineTextAlignment(.leading)
                        .truncationMode(.tail)
                        .fixedSize()
                        .lineLimit(1)
                        .shadow(color: Color.black.opacity(0.3), radius: 2, x: 2, y: 2)
                        .background(
                            Text("US")
                                .font(.custom("Termina Test-Black", size: 40))
                                .fontWeight(.heavy)
                                .foregroundColor(Color.init(hex: "7743DB"))
                                .multilineTextAlignment(.leading)
                                .frame(maxWidth: .infinity)
                                .blur(radius: 0.8)
                                .offset(x:19, y:-3)
                                .padding(.vertical, 100)
                        )
                    Text("ABOUT")
                        .font(.custom("Termina Test-Black", size: 40))
                        .fontWeight(.heavy)
                        .foregroundColor(Color.init(hex: "7743DB"))
                        .padding(.vertical, 100)
                        .offset(x:19, y:-3)
                        .multilineTextAlignment(.leading)
                        .truncationMode(.tail)
                        .fixedSize()
                        .lineLimit(1)
                    
                    Text("YOURS")
                        .font(.custom("Termina Test-Black", size: 40))
                        .fontWeight(.heavy)
                        .foregroundColor(Color.white)
                        .padding(.vertical, 100)
                        .offset(x:19, y:-3)
                        .multilineTextAlignment(.leading)
                        .truncationMode(.tail)
                        .fixedSize()
                        .lineLimit(1)
                        .shadow(color: Color.black.opacity(0.3), radius: 2, x: 2, y: 2)
                        .background(
                            Text("YOURS")
                                .font(.custom("Termina Test-Black", size: 40))
                                .fontWeight(.heavy)
                                .foregroundColor(Color.init(hex: "7743DB"))
                                .multilineTextAlignment(.leading)
                                .frame(maxWidth: .infinity)
                                .blur(radius: 0.8)
                                .offset(x:19, y:-3)
                                .padding(.vertical, 100)
                        )
                }
                
                .frame(width: 350)
                
                HStack{
                    Text("ABOUT")
                        .font(.custom("Termina Test-Black", size: 40))
                        .fontWeight(.heavy)
                        .foregroundColor(Color.white)
                        .padding(.vertical, 100)
                        .offset(x:-50, y:-215)
                        .multilineTextAlignment(.leading)
                        .truncationMode(.tail)
                        .fixedSize()
                        .lineLimit(1)
                        .shadow(color: Color.black.opacity(0.3), radius: 2, x: 2, y: 2)
                        .background(
                            Text("ABOUT")
                                .font(.custom("Termina Test-Black", size: 40))
                                .fontWeight(.heavy)
                                .foregroundColor(Color.init(hex: "7743DB"))
                                .multilineTextAlignment(.leading)
                                .frame(maxWidth: .infinity)
                                .blur(radius: 0.8)
                                .offset(x:-50, y:-215)
                                .padding(.vertical, 100)
                        )
                    Text("YOURSELF")
                        .font(.custom("Termina Test-Black", size: 40))
                        .fontWeight(.heavy)
                        .foregroundColor(Color.init(hex: "7743DB"))
                        .padding(.vertical, 100)
                        .offset(x:-50, y:-215)
                        .multilineTextAlignment(.leading)
                        .truncationMode(.tail)
                        .fixedSize()
                        .lineLimit(1)
                }
                
                .frame(width: 350)
                if(screen == "one")
                {
                    FloatingIcon(iconName: "calander", screenNo: screen)
                        .padding(.leading, 16)
                        .offset(x:140, y:-480)
                    FloatingIcon(iconName: "cake", screenNo: screen)
                        .padding(.leading, 16)
                        .offset(x:-150, y:-435)
                }
                else if(screen == "two")
                {
                    FloatingIcon(iconName: "telescope", screenNo: screen)
                        .padding(.leading, 16)
                        .offset(x:140, y:-480)
                    FloatingIcon(iconName: "wine", screenNo: screen)
                        .padding(.leading, 16)
                        .offset(x:-150, y:-435)
                }
            }
        }
        else
        {
            VStack{
                HStack{
                    Text("LET'S ADD")
                        .font(.custom("Termina Test-Black", size: 40))
                        .fontWeight(.heavy)
                        .foregroundColor(Color.init(hex: "7743DB"))
                        .padding(.vertical, 100)
                        .offset(x:19, y:250)
                        .multilineTextAlignment(.leading)
                        .truncationMode(.tail)
                        .fixedSize()
                        .lineLimit(1)
                    
                    Text("YOUR")
                        .font(.custom("Termina Test-Black", size: 40))
                        .fontWeight(.heavy)
                        .foregroundColor(Color.white)
                        .padding(.vertical, 140)
                        .offset(x:19, y:250)
                        .multilineTextAlignment(.leading)
                        .truncationMode(.tail)
                        .fixedSize()
                        .lineLimit(1)
                        .frame(maxWidth: .infinity)
                        .shadow(color: Color.black.opacity(0.3), radius: 2, x: 2, y: 2)
                        .background(
                            Text("YOUR")
                                .font(.custom("Termina Test-Black", size: 40))
                                .fontWeight(.heavy)
                                .foregroundColor(Color.init(hex: "7743DB"))
                                .multilineTextAlignment(.leading)
                                .frame(maxWidth: .infinity)
                                .blur(radius: 0.8)
                                .offset(x:19, y:250)
                                .padding(.vertical, 100)
                        )
                }
                
                .frame(width: 350)
                
                HStack{
                    Text("LET'S ADD")
                        .font(.custom("Termina Test-Black", size: 40))
                        .fontWeight(.heavy)
                        .foregroundColor(Color.white)
                        .padding(.vertical, 100)
                        .offset(x:0, y:-3)
                        .multilineTextAlignment(.leading)
                        .truncationMode(.tail)
                        .fixedSize()
                        .lineLimit(1)
                        .shadow(color: Color.black.opacity(0.3), radius: 2, x: 2, y: 2)
                        .background(
                            Text("LET'S ADD")
                                .font(.custom("Termina Test-Black", size: 40))
                                .fontWeight(.heavy)
                                .foregroundColor(Color.init(hex: "7743DB"))
                                .multilineTextAlignment(.leading)
                                .frame(maxWidth: .infinity)
                                .blur(radius: 0.8)
                                .offset(x:0, y:-3)
                                .padding(.vertical, 100)
                        )
                    Text("YOUR")
                        .font(.custom("Termina Test-Black", size: 40))
                        .fontWeight(.heavy)
                        .foregroundColor(Color.init(hex: "7743DB"))
                        .padding(.vertical, 100)
                        .offset(x:0, y:-3)
                        .multilineTextAlignment(.leading)
                        .truncationMode(.tail)
                        .fixedSize()
                        .lineLimit(1)
                    
                    Text("BIO")
                        .font(.custom("Termina Test-Black", size: 40))
                        .fontWeight(.heavy)
                        .foregroundColor(Color.white)
                        .padding(.vertical, 100)
                        .offset(x:0, y:-3)
                        .multilineTextAlignment(.leading)
                        .truncationMode(.tail)
                        .fixedSize()
                        .lineLimit(1)
                        .shadow(color: Color.black.opacity(0.3), radius: 2, x: 2, y: 2)
                        .background(
                            Text("BIO")
                                .font(.custom("Termina Test-Black", size: 40))
                                .fontWeight(.heavy)
                                .foregroundColor(Color.init(hex: "7743DB"))
                                .multilineTextAlignment(.leading)
                                .frame(maxWidth: .infinity)
                                .blur(radius: 0.8)
                                .offset(x:0, y:-3)
                                .padding(.vertical, 100)
                        )
                }
                
                .frame(width: 350)
                
                HStack{
                    Text("ADD YOUR")
                        .font(.custom("Termina Test-Black", size: 40))
                        .fontWeight(.heavy)
                        .foregroundColor(Color.white)
                        .padding(.vertical, 100)
                        .offset(x:-0, y:-215)
                        .multilineTextAlignment(.leading)
                        .truncationMode(.tail)
                        .fixedSize()
                        .lineLimit(1)
                        .shadow(color: Color.black.opacity(0.3), radius: 2, x: 2, y: 2)
                        .background(
                            Text("ADD YOUR")
                                .font(.custom("Termina Test-Black", size: 40))
                                .fontWeight(.heavy)
                                .foregroundColor(Color.init(hex: "7743DB"))
                                .multilineTextAlignment(.leading)
                                .frame(maxWidth: .infinity)
                                .blur(radius: 0.8)
                                .offset(x:0, y:-215)
                                .padding(.vertical, 100)
                        )
                    Text("BIO")
                        .font(.custom("Termina Test-Black", size: 40))
                        .fontWeight(.heavy)
                        .foregroundColor(Color.init(hex: "7743DB"))
                        .padding(.vertical, 100)
                        .offset(x:0, y:-215)
                        .multilineTextAlignment(.leading)
                        .truncationMode(.tail)
                        .fixedSize()
                        .lineLimit(1)
                }
                
                .frame(width: 350)
                FloatingIcon(iconName: "bulb", screenNo: screen)
                    .padding(.leading, 16)
                    .offset(x:140, y:-480)
                FloatingIcon(iconName: "whatnot", screenNo: screen)
                    .padding(.leading, 16)
                    .offset(x:-150, y:-435)
            }
            .offset(y:70)
        }
    }
}

